### ISSUE TITLE
WARN[0201] Failed login attempt User=Inventur

### ISSUE THREAD

**Issue by momo-aux** [openlab-aux/lsmsd-frickelclient#4]
I installed MongoDB
did 
go get lsmsd
pip installed frickelclient and changed settings.

No I get the error whenever I add an item.

I added a user with Name and Password Inventur to the MongoDB lsmsd_ with mongoclient

What else do I need to do to get this running?

**Comment by momo-aux** [comment]
```
SECRET_KEY = "lel"
LSMSD_HOST = "http://localhost:8080/"
LSMSD_USER = "Inventur"
LSMSD_PASS = "Inventur"
KLAUSKLEBER_AAS_URL = "http://labtop.openlab.lan:2342/"

```

**Comment by momo-aux** [comment]
lsmsd conf
```
; This is an example config for the lsms server.

[Network]
ListenTo = ":8080"
[Crypto]
Enabled = false
Certificate = "./certfile.pem"
KeyFile = "./keyfile.key"
Pepperfile = "./.pepper"
[Database]
Server = "localhost"
DB = "lsmsd_"
[Mail]
Enabled = false
StartTLS = true
ServerAddress = ""
Port = 587
Username = ""
Password = ""
EMailAddress = ""
Admin = ""
[Logging]
Level = "Info"

```

**Comment by momo-aux** [comment]
![client](https://cloud.githubusercontent.com/assets/5537530/25805304/a36f5634-33ff-11e7-8bc8-a5692d859687.png)

**Comment by momo-aux** [comment]
Console log lsmsd
```
> lsmsd.exe
INFO[0000] lsmsd starting                                Version=0.1
INFO[0000] Test database connection …
INFO[0000] Connection successful
[restful] 2017/05/08 14:57:06 log.go:33: [restful/swagger] listing is available at /apidocs.json
[restful] 2017/05/08 14:57:06 log.go:33: [restful/swagger] /apidocs/ is mapped to folder ./swagger/dist/
INFO[0000] lsms started successfully                     Address=":8080" TLS=false
WARN[0023] Failed login attempt                          User=Inventur
```

**Comment by momo-aux** [comment]
log frickelclient

```
> python manage.py runserver
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [08/May/2017 15:00:27] "POST /dinge/add HTTP/1.1" 500 -
127.0.0.1 - - [08/May/2017 15:05:15] "GET /dinge/add HTTP/1.1" 200 -
127.0.0.1 - - [08/May/2017 15:05:34] "POST /dinge/add HTTP/1.1" 500 -
```

**Comment by glaxx** [comment]
@waaaaargh Does the frickelclient have an User Registration Page?

@momo-aux I'm not quite sure yet how to solve your problem here. In my POV you just have to add an User like [my code](https://github.com/openlab-aux/lsmsd/blob/master/webservice/user.go#L173) does. Which can be also triggered by an POST Request on the /users/-Endpoint. You may want to see your [local swagger documentation (http://yourlsmsdinstance/apidocs/).

**Comment by momo-aux** [comment]
Ah lol, the user is not a database user but a lsms user.
I thought it is a database user and I have to add it to MongoDB.
Ok, after using the swagger UI to post to users I end up with a running instance now :-)

Perhaps you should add that to the installation notes.
Like:

Open http://localhost:8080/apidocs/?url=http://localhost:8080/apidocs.json#!/users/CreateUser
Enter:
```
{
  "Name": "Inventur",
  "EMail": "inventur@local",
  "Password": "Inventur"
}
```

Hit "Try it out" to create the user with the given parameters.
